"use client";
import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div lang="en">
      <section className={inter.className}>
        <ThemeProvider defaultTheme="light" enableSystem={true}>
          <main>{children}</main>
        </ThemeProvider>
      </section>
    </div>
  );
}
