"use client"
import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Providers } from "@lib/providers";
import { useEffect, useState } from "react";
import { Toaster } from "react-hot-toast";
import { ProgressBar } from "@components/loading/ProgressBar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [theme, setTheme] = useState(loadTheme());
  const [loading, setLoading] = useState(true);

  function loadTheme() {
    const isServer = typeof window === "undefined";
    if (!isServer) {
      return localStorage.getItem("theme") || "dark";
    }
  }

  useEffect(() => {
    const element = document.documentElement;
    if (localStorage.getItem("theme") === "dark") {
      element.classList.add("dark");
    } else if (localStorage.getItem("theme") === "light") {
      element.classList.remove("dark");
    } else {
      element.classList.add("dark");
    }
  }, [theme]);

  useEffect(() => {
    // This code will run on the client side after hydration.
    setLoading(false); // Set loading to false once fully hydrated.
  }, []);

  return (
    <html lang="en" className="dark">
      {/* className={inter.className} */}
      <body className="bg-white dark:bg-[#121212] ">
        <main>
          <Providers>
            <Toaster />
            <ProgressBar loading={loading} />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
