"use client";
import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Providers } from "@lib/providers";
import { Toaster } from "react-hot-toast";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className="dark">
      {/* className={inter.className} */}
      <body className="bg-white dark:bg-[#121212] ">
        <main>
          <Providers>
            <Toaster />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
